import type { Story } from "@/lib/stories/types";

export const aroostookWarStory: Story = {
  slug: "aroostook-war",
  title: "A line convenient to both",
  dek: "In February 1839 the lieutenant-governor of New Brunswick told Maine to pull an armed posse off the Aroostook or he would occupy the disputed territory. On 3 March Congress appropriated ten million dollars and, if invasion was imminent, a ceiling of fifty thousand volunteers. The papers of that winter contain an arrest, a parole, and a threat. They do not contain a battle. The line signed in August 1842 was a conventional boundary, not a finding that the highlands of 1783 had been located.",
  hook: "The United States and Britain fought a bloodless war over the forests of Maine.",
  yearLabel: "1839–1842",
  published: "2026-09-26",
  updated: "2026-09-26",
  sourcesNote:
    "This essay is original prose. The 1783 highlands clause is the National Archives transcription of Article 2 of the Treaty of Paris, signed 3 September 1783. The St. Croix commission’s declaration of 25 October 1798, the Treaty of Ghent’s fifth article, the convention of 29 September 1827, the King of the Netherlands’ opinion of 10 January 1831, and the Senate’s refusal to treat that opinion as obligatory follow the historical outline transmitted with the President’s message of 20 March 1838, as printed by the American Presidency Project. Henry Fox’s note of 10 January 1838, in the same message, is the source for the statement that both governments had agreed the award bound neither party, and for the British proposal of an equal division. The February 1839 arrests, the parole, the letters of Sir John Harvey, John Fairfield, George Frederick Street, and Charles Jarvis, and the Forsyth–Fox memorandum of 27 February 1839 are taken from the President’s messages of 16 and 27 February 1839. The arrangement of 23 and 25 March 1839 is John Forsyth’s recital of 25 March 1840, which attributes it to the agency of General Winfield Scott; this essay uses that recital and has not reprinted Scott’s own March letters. Where the message of 16 February counts the land agent and two other citizens, Street’s letter of 17 February and Jarvis’s of 19 February count three, and the parole of 18 February is addressed to four men, the counts stay. The act of 3 March 1839 is United States Statutes at Large, volume 5, chapter 89. The treaty of 9 August 1842 is the Avalon Project text of the public compilation, including Article V’s three hundred thousand dollars. That compilation’s header dates the exchange of ratifications at London to 15 October 1842; a Library of Congress catalog note on an 1842 printing dates the exchange to 13 October. Both dates stay. The British day of ratification is not readable in the transcription used here, and it is not supplied. The figures 7,015 and 5,012 square miles are the Office of the Historian’s, not a sentence of the treaty. The Maine State Library’s public note is the source for the labels Bloodless War and Pork and Beans War; they are treated as labels, not as a casualty return or a ration list. We have not scraped Reddit, Wikipedia, or another site’s essay, and we invent no dialogue in the camps or in the legislature.",
  sections: [
    {
      paragraphs: [
        "The hook is a war that earns its name by not happening. The United States and Britain, so the line goes, fought over the pine of northern Maine, called out men, spent a political fortune, and never fired. The Maine State Library’s public note still files the episode as the Bloodless War or the Pork and Beans War. Those are labels. A label is not a return of who was in camp, and it is not a report of a battle that the diplomatic papers forgot to mention.",
        "The file is older than the winter of 1839 and duller than a nickname. Article 2 of the Treaty of Paris, signed on 3 September 1783, tried to stop future boundary disputes by describing one. From the northwest angle of Nova Scotia — “that Angle which is formed by a Line drawn due North from the Source of St. Croix River to the Highlands” — the line was to follow “the said Highlands which divide those Rivers that empty themselves into the river St. Lawrence, from those which fall into the Atlantic Ocean,” to the northwesternmost head of the Connecticut. The highlands were not a range the negotiators had walked. They were a job for whoever next had to find a height of land that shed water two ways, in a country of bogs, portages, and more than one river that could be called the St. Croix. In the winter of 1839 the job was still open, and men with axes were cutting the timber on the ground the sentence had not assigned.",
      ],
    },
    {
      heading: "What the commissions could settle",
      paragraphs: [
        "One piece of the sentence did get a monument. Doubts about which river was the St. Croix were sent, by the fifth article of the treaty of November 1794, to a commission whose decision both sides agreed to treat as final. The historical outline transmitted with the President’s message of 20 March 1838 records the result: on 25 October 1798 the commissioners declared that the northern branch, spelled there Cheputnaticook, of a river called Scoodiac was the St. Croix the treaty meant. The treaty of 1842 starts from the monument those commissioners left at the source. It does not reopen their river.",
        "The highlands were another matter. At the Treaty of Ghent, 24 December 1814, the line from that source to the Lake of the Woods was still unfixed. Article 5 authorized commissioners to find the northwest angle of Nova Scotia and the northwesternmost head of the Connecticut, in conformity with 1783, and to mark the boundary. The same outline says commissioners were appointed in 1815 and 1816, sat for several years, and agreed on none of it. In 1822 they made separate reports. A convention of 29 September 1827 sent the points of difference — three of them — to a friendly sovereign. The two governments chose the King of the Netherlands. His award, “or rather written opinion,” as the outline insists on calling it, is dated 10 January 1831.",
      ],
    },
    {
      heading: "An opinion the Senate would not execute",
      paragraphs: [
        "On 7 December 1831 the President sent that opinion to the Senate and reported that Britain was willing to abide by it. The Senate determined that the decision was not obligatory and refused its advice and consent. In June 1832 it resolved that the President open a new negotiation to ascertain the boundary according to the treaty of peace. The American explanation, given that July to the British chargé, Mr. Bankhead, was that the resolution rested on a conviction: the arbiter, instead of deciding the questions put to him, had recommended a specified compromise. Britain’s minister later put the same point in his own words. Sir Charles Vaughan, in February 1834, said the arbiter had declared it impossible to find a spot, or trace a line, that fulfilled every condition the treaty set for the northwest angle and for the highlands, and that neither the British line nor the American line could be adjudged the true one without departing from equity. London wanted the parts of the opinion it liked treated as binding. Washington, after the Senate’s refusal, would not.",
        "By 10 January 1838 Henry Fox, the British minister in Washington, was writing as if that argument had closed. Both governments, he said, had agreed to consider the award binding on neither party. Britain, “despairing of the possibility of drawing a line that shall be in literal conformity with the words of the treaty of 1783,” asked for a conventional boundary and an equal division of the thing in dispute. The United States had answered that it had no power to agree to a cession Maine would regard as its own land, without Maine’s consent. It had been willing to ask Maine about another conventional line, the St. John from source to mouth. Fox rejected that line as worse, for Britain, than giving the United States its entire claim: Maine would take the disputed country south of the river and, in exchange for the country north of it, a district of New Brunswick that he called smaller and more valuable. The federal outline stated the rule the administrations had been using. The United States could negotiate the treaty line, or arbitrate it. It was not competent, unless perhaps under an imperious public necessity, to bargain away territory Maine was entitled to under the true construction of 1783, without the state’s consent. The winter of 1839 is what that impasse looked like once the axes were already in the trees.",
      ],
    },
    {
      heading: "A house, a parole, two datelines",
      paragraphs: [
        "President Van Buren’s message of 16 February 1839 describes the trespass before it describes any army. A numerous band, chiefly from the adjoining British provinces, and without the authority or sanction of the provincial government, had been cutting and destroying a very large quantity of timber on the part of the disputed territory watered by the Aroostook and claimed by Maine. The governor laid it before the legislature. Under a resolve, he sent the state land agent with a force “deemed adequate” to stop the cutting and hold the timber. After doing part of that work, the land agent was seized by a band of the trespassers at a house claimed to be inside Maine’s jurisdiction, where he had gone to meet the land agent of New Brunswick, and was conveyed as a prisoner to Frederickton — the message’s spelling — with two other citizens of the state.",
        "The papers the President sent on 27 February do not leave the seizure in that one sentence, and they do not keep the count. A parole dated 18 February at Frederickton, over Harvey’s signature, is addressed to four men: Rufus McIntire, Gustavus G. Cushman, Thomas Bartlett, and Ebenezer Webster. The pledge under it is a single “we,” witnessed by W. Earl, not four separate signatures in the copy Congress received. The offense, Harvey writes, had been pronounced by the law officers to be one against the law of nations and of treaties rather than against the municipal law of the province, so they were “state offenders,” to be reported to London. Meanwhile he directed that they return to Maine on a pledge to present themselves when required. The message of 16 February had said the land agent and two other citizens. Street’s letter of 17 February counts “three gentlemen.” Jarvis, answering on the 19th, counts McIntire “and the two other gentlemen with him.” The parole of the 18th is addressed to four. Almost Lore will not drop a name to make the arithmetic match, and it will not add a man the earlier message did not count.",
        "Harvey’s letter to Governor John Fairfield, the same day, is the threat the hook compresses into a war. If Maine wished the friendly relations of Great Britain and the United States undisturbed, the armed force then understood to be inside the disputed territory had to be withdrawn immediately. Otherwise he had no alternative but to take military occupation, protect British subjects, and support the civil authorities in arresting anyone who claimed to exercise jurisdiction there. He also required that British subjects arrested for trespass be given up to New Brunswick courts, and that if James Maclauchlan, “warden of the disputed territory,” had been detained, that officer be enlarged and the grounds explained. Fairfield’s answer of 21 February refuses the demand that the arrested trespassers be given up. The persons named, he writes, were in the custody of the law, and he had neither the disposition nor the authority to interfere. On Maclauchlan — Fairfield calls him provincial land agent — and on an assistant, Tibbets, he had advised release on the same terms as McIntire’s, a parole to return to Bangor if the state required it. The rest of Harvey’s letter, including the demand that the armed force leave, he sends back to a reply of the 18th. This essay has not rebuilt that earlier reply from the governor’s pointer.",
        "Under those two letters sit two other datelines, and they are not the same place. On 17 February George Frederick Street, solicitor-general of the province, writes from “the mouth of the Arestook,” which he locates on the St. John in New Brunswick, to the officer commanding the armed force. He is surprised that the force entered the disputed territory without notice, seized and maltreated British subjects, and held prisoners. Unless it removes itself, discharges the prisoners, and stops exercising any authority the British government has not authorized, every person of the party who can be found will be detained. A large military force, he writes, is assembling; part has arrived. He would rather avoid bloodshed. If the party leaves quietly, the troops need not move farther. If it does not, military possession will be taken, “and the consequences must be upon your own heads.” He adds that the three gentlemen taken by “some of our people” have been forwarded to Frederickton by the magistrates. The warden, he understands, went out to explain this and has not come back.",
        "Charles Jarvis, signing as land agent, answers on 19 February from the confluence of the St. Croix stream and the Aroostook, Township No. 10, which he calls the State of Maine. Street, he writes, must have been misinformed about the place, or he would not have addressed such a paper to a citizen of Maine. The officer Street means was arrested for serving a precept on a citizen of Maine and sent to Augusta; Jarvis does not have him. If Street is not mistaken about the place, then Jarvis has one answer to the threat. He is there under the executive of the state, he will remain until that authority orders otherwise, and he will consider the approach of an armed force “an act of hostility, which will be met by me to the best of my ability.” The ground he claims for being there is specific, and it is his claim, not a judgment this essay has tried: the land was run out into townships by Massachusetts and covered by Massachusetts grants before Maine was separated from that state.",
        "Fairfield, reporting to the legislature on 21 February, treats Jarvis’s reply as the right spirit and then gives the numbers he has. McIntire and his assistants are released, on the parole. He has advised the same for Maclauchlan. The land agent’s force on the Aroostook has been reinforced by about 600 men, “making the whole force now about 750.” A letter from Jarvis dated the 19th, before that reinforcement, described a company of only 100, temporary defenses of logs, and a prediction: by noon the next day, 100 men would make the position good against 500, so retreat was out of the question. The governor also reports a draft of 1,000 men from the third division, already at a rendezvous and waiting for the order to march, and a detachment of the second division to be ordered forward, probably on the Monday following. These are the governor’s approximations and a quotation of his land agent. They are not a roll this essay has added up, and they are not a battle. The papers laid before Congress do not record that the 500 men in Jarvis’s sentence arrived, or that anyone tested the log works.",
      ],
    },
    {
      heading: "A recommendation, and a ceiling of fifty thousand",
      paragraphs: [
        "The same message of 27 February carries a memorandum signed that day by John Forsyth, Secretary of State, and by Fox. Van Buren’s covering note says the British minister acts without specific authority from his government, so the paper “has but the force of recommendation” on New Brunswick and on Maine. The two sides open by contradicting each other. British authorities consider it already understood that the disputed territory stays under exclusive British jurisdiction until the boundary is settled. The United States considers that there was no such agreement, only a mutual understanding that, pending negotiation, the jurisdiction either party already exercised over small portions should not be enlarged. Until a discussion in Washington and London can settle that, the memorandum recommends a temporary rule. British officers will not seek to expel by military force the armed party Maine has sent into the district bordering the river — spelled here Restook, not Aroostook, and not Street’s Arestook. Maine will, voluntarily and without needless delay, withdraw beyond the disputed territory any armed force now within it. If trespassers have to be dispersed later, or public property protected, the operation will be by concert, jointly or separately, as Maine and New Brunswick agree. Civil officers taken by either side will be released. Nothing in the memorandum is to fortify or weaken either party’s claim to the ultimate possession.",
        "Congress answered the winter with a statute, not with a declaration that war had begun. The act of 3 March 1839 is chapter 89 of volume 5 of the Statutes at Large. Its title gives the President additional powers for the defense of the United States, in certain cases, against invasion. The first section authorizes him to resist any attempt by Great Britain to enforce, by arms, her claim to exclusive jurisdiction over the disputed part of Maine, and for that purpose to use the naval and military forces and such militia as he thinks advisable. A later section is the sentence people remember, and it is conditional. In the event of actual invasion, or of imminent danger of invasion discovered in his opinion to exist before Congress can meet, he may accept volunteers not exceeding fifty thousand. Ten million dollars are appropriated and placed at his disposal to execute the act, to be raised if needed by stock at not more than five percent, reimbursable after five years from the first of January next. Eighteen thousand dollars are appropriated for the outfit and salary of a special minister to Great Britain, if he deems it expedient to appoint one. The provisions last until sixty days after the next Congress meets, and no longer. The popular compression — Congress raised fifty thousand men and voted ten million dollars for a timber war — merges a ceiling that applied only if invasion was actual or imminent, a borrowing authority, a diplomat’s outfit, and a sunset. The statute is a recess power. It is not a muster.",
      ],
    },
    {
      heading: "What the March arrangement left in the woods",
      paragraphs: [
        "The recommendation of 27 February was not the last paper. On 25 March 1840 Forsyth, answering a fresh British protest, recited a further arrangement “agreed to on the 23d and 25th of March” 1839 through the agency of General Winfield Scott. This essay has not reprinted Scott’s own letters from that month. The terms below are the Secretary of State’s recital a year later, and they are terms. Harvey bound himself not to seek, without renewed instructions from his government, to take military possession of the territory or to expel from it by military force Maine’s armed civil posse or Maine’s troops. Fairfield agreed that, without renewed instructions from the legislature, no attempt would be made to disturb by arms New Brunswick’s possession of the Madawaska settlements, or to interrupt the usual communications between that province and the upper provinces. Possession and jurisdiction were to remain unchanged: each party in fact holding part of the disputed territory, each denying the other’s right to do so. With that understanding, Maine was to withdraw her military force without unnecessary delay, leaving only, under a land agent, a small civil posse, armed or unarmed, to protect the timber recently cut and to prevent further depredations.",
        "A year on, the two governments were still arguing about what that posse was allowed to be. Fox’s note of 13 March 1840 says Maine must put itself back where it stood before the agreements: retire from the valley of the St. John, confine itself to the valley of the Aroostook, occupy that valley only temporarily to prevent depredations, and build no fortifications, roads, or permanent settlements. Until then, Britain will make the military arrangements required to protect its rights, and if collision follows, the responsibility “will rest with the people and Government of the United States.” Forsyth’s answer of 25 March refuses both of Fox’s enlargements. Nothing in the Fairfield–Harvey agreement, he writes, draws a line inside the disputed territory beyond which the civil posse may not go. The posse’s work is the timber, in every part of the territory where the timber needs protecting, limited by the promise not to disturb the Madawaska settlements as they actually stood, or the usual communications. He puts a settlement on the north side of the St. John, and a Maine station at the mouth of Fish River, twenty-five miles apart, and he will not let the first swallow the second. He also says British troops and military works have been moving in the disputed territory, and that those movements are inconsistent with an arrangement whose object was to get the soldiers out. Each note predicts misfortune if the other side persists. Neither note attaches a battle to the prediction.",
      ],
    },
    {
      heading: "Convenient, and paid for",
      paragraphs: [
        "The instrument that closed the sentence was signed at Washington on 9 August 1842 by Daniel Webster and Lord Ashburton. Its preamble is a decision to stop deciding. Portions of the 1783 line “have not yet been ascertained and determined, notwithstanding the repeated attempts which have been heretofore made for that purpose.” It is now thought in the interest of both parties, “avoiding further discussion of their respective rights” under that treaty, to agree on a conventional line “such as may be convenient to both Parties, with such equivalents and compensations, as are deemed just and reasonable.” The highlands of 1783 are not found in that paragraph. They are set aside. The same preamble recites two further objects, suppression of the African slave trade and the mutual giving up of fugitives charged with specified crimes. Those articles are not this boundary, and they are not retold here.",
        "Article I draws the substitute. It begins at the monument at the source of the St. Croix fixed by the commissioners under the fifth article of the treaty of 1794, runs north along the exploring line the two governments’ surveyors marked in 1817 and 1818, and meets the St. John in the middle of the channel. It follows that channel up to the St. Francis, and the St. Francis and its lakes to the outlet of Lake Pohenagamook. From there the line is geometry rather than a watershed: a straight line to a point on the northwest branch of the St. John ten miles from the main branch, unless that point would lie less than seven miles from the crest dividing St. Lawrence waters from St. John waters, in which case the point recedes until it is seven miles from the crest; then a straight course, about south eight degrees west, to where the parallel of 46°25' north crosses the southwest branch; then up that branch to its source in the highlands at the Metjarmette Portage; then along highlands that divide St. Lawrence waters from Atlantic waters to the head of Hall’s Stream; then down that stream to the old line Valentine and Collins had surveyed before 1774, understood as the boundary between New York and Vermont and the province of Canada, and west along that line to the St. Lawrence. The treaty is doing, with miles and a parallel, what the Senate had refused to let the King of the Netherlands do by recommendation. It is choosing a line the words of 1783 did not draw. This time the two governments signed, and Article V records the assent of Maine and Massachusetts as something the United States paid for.",
        "The timber is in the treaty, not only in the posse’s orders. Where the St. John is the boundary, Article III leaves the navigation free and open. Produce of the forest — logs, lumber, timber, boards, staves, or shingles — and unmanufactured agricultural produce grown on the Maine waters of the St. John may go down to the sea, and through New Brunswick is to be dealt with as if it were the produce of the province. Article IV confirms grants already made by either party on land that falls to the other, and possessory claims from more than six years’ possession and improvement before the date of the treaty. People already on the ground were not a blank the line could erase. Article V is the money. New Brunswick had received sums “with the intention of preventing depredations on the forests,” carried to a disputed-territory fund that was to be divided once the boundary was final. A correct account is to be delivered within six months of ratification, and Maine’s and Massachusetts’s portions paid over through Washington. The United States further agrees to satisfy those states for expenses incurred in protecting the territory and in a survey of it in 1838, and to pay them three hundred thousand dollars, in equal moieties, on account of their assent to the line and the equivalents received from Britain.",
        "The Office of the Historian’s milestone note on the treaty says the division of the disputed territory gave 7,015 square miles to the United States and 5,012 to Great Britain. Those integers are not in the articles. Adding them produces 12,027, which is arithmetic on that note, not a sentence Webster and Ashburton signed. This essay has not remeasured the map. What the text does sign is a line, a right to float timber, a confirmation of settlers, and a sum paid to two states for agreeing to stop insisting on the other line.",
        "The compilation header used here dates the Senate’s advice and consent to 20 August 1842, the United States ratification to 22 August, the exchange of ratifications at London to 15 October, and the proclamation to 10 November. A Library of Congress catalog note on an 1842 printing dates the exchange to 13 October and the proclamation to the same 10 November. Both exchange dates stay. The day Britain itself ratified is not readable in the transcription this essay used. It is not filled in from memory. Article VI orders two commissioners, one appointed by each side, to meet at Bangor on the first of May next, or as soon after as may be, and to mark the line. The order is in the treaty. Their joint report is not retold here.",
      ],
    },
    {
      heading: "Why the hook is not the essay",
      paragraphs: [
        "A compressed line needs a war and a mercy. Empires march, somebody sensible holds them, the only casualty is a legend about pork and beans. The papers will not supply the battle that legend requires. They will supply a treaty article that could not be walked, an arbiter who said the article could not be satisfied and was then held to have recommended rather than decided, a land agent seized on his way to a meeting and released on parole, a solicitor-general writing from one river-mouth and a land agent answering from another, a governor’s “about 750,” and a statute whose fifty thousand volunteers existed only if the President found an invasion actual or imminent before Congress could sit. General Scott’s agency, in the recital Forsyth gave a year later, left a civil posse in the timber and the soldiers withdrawn, with each side still denying the other’s right to the ground it held.",
        "Nothing in that file is a certificate that the winter killed no one. Camps, drafts, and log works can cost lives the diplomatic notes do not itemize, and this essay will not invent a death, or a zero, to decorate the library’s label. The near-miss is the distance between Jarvis’s sentence — an approach would be hostility, and he would meet it — and the absence, in the papers Congress was given, of the approach. What ended the dispute was not a volley that failed to be fired. It was a preamble that declined to find the highlands, a conventional line, and three hundred thousand dollars for the states that assented to it.",
      ],
    },
  ],
};
