import type { Story } from "@/lib/stories/types";

export const carolineAffairStory: Story = {
  slug: "caroline-affair",
  title: "The Caroline at Schlosser",
  dek: "On the night of 29 December 1837 a British party burned the American steamer Caroline at a landing on the New York side of the Niagara. Amos Durfee was killed on the dock. The near-war was not a second battle at the river. It was a murder charge, a boast, and a sentence about necessity that the two governments adopted without agreeing the raid had earned it.",
  hook: "Britain set an American steamboat on fire and sent it over Niagara Falls, and the two countries nearly went to war.",
  yearLabel: "1837–1842",
  published: "2026-09-26",
  updated: "2026-09-26",
  sourcesNote:
    "This essay is original prose. The 1837 facts and the 1842 notes follow Hunter Miller’s Treaties and Other International Acts of the United States of America, volume 4 (Government Printing Office, 1934), which reprints the Webster–Ashburton correspondence and extracts John Bassett Moore’s Digest for the seizure, the master’s deposition, and the later investigation. The trial account follows the Historical Society of the New York Courts summary of People v. McLeod (1841). Where the master’s first numbers and the later investigation disagree about who was missing, both are named. Where Moore dates the diplomatic turn to March 1841 and the court history dates the arrest to November 1840, both dates stay. The claim that the hull went over the falls is the claim in the early reports and in the title of Andrew Drew’s 1864 narrative; it is not treated here as a survey of the brink. We have not scraped Reddit, Wikipedia, or another site’s essay, and we invent no dialogue in the boats or in the Utica courtroom.",
  sections: [
    {
      paragraphs: [
        "The hook is a picture. An American steamer, fired by a British cutting-out party, goes over Niagara Falls, and two countries that are officially at peace spend years not quite fighting about it. The picture is what traveled. It made a small boat large, and it made a file of notes look like a battle that simply failed to start.",
        "The file is less obedient. On the night of 29 December 1837 a party sent from the Canadian shore did board the steamer Caroline at Schlosser, on the New York side of the Niagara, while the Upper Canadian rebellion was using the river as a supply line. Amos Durfee, an American, was killed on the dock. The boat was burned and cast into the current above the cataract. Whether the hull itself went over the brink is where the prints and the later investigation part company. Ashburton, the British negotiator, later wrote that the case had more than once endangered the peace. The danger in that sentence is not a second volley at the landing. It is the years after: a boast, a state murder charge, and a rule about self-defense that Daniel Webster wrote down and that both governments then agreed to recite without agreeing that this raid had met it.",
      ],
    },
    {
      heading: "A rebellion that used the river",
      paragraphs: [
        "In December 1837 the rebellion in Upper Canada had already been broken on the Canadian side of the line and had not stayed there. William Lyon Mackenzie and others crossed into New York, held meetings in Buffalo, and asked in public for arms, ammunition, and volunteers. The United States marshal for the northern district of New York went to Buffalo to enforce the neutrality laws. On 28 December he reported what he had found: some two or three hundred men, mostly from the American side of the river, encamped on Navy Island in Upper Canada, armed, under a man styling himself General Van Rensselaer, of Albany, with the camp still growing. Warrants had been issued. They had not been served. Moore’s digest, which is the summary Hunter Miller prints with the later treaty notes, puts the camp’s strength, after those accessions, at about a thousand. That is the marshal’s picture, passed through the digest. It is not a roll this essay has counted.",
        "Navy Island sits in the Niagara just above the falls, on the Canadian side of the boundary, within sight of both shores. The Caroline was the boat that made the island a camp instead of a stranding. She was a small American steamer — Miller’s note, which is willing to be definite about the hull, gives her as 46 tons and 71 feet — employed by the men at Black Rock and on the island to keep touch with the New York mainland. On 29 December, by her master’s deposition, she left Buffalo for Schlosser, also in New York. She touched at Black Rock and put up the American flag. Muskets were fired at her from the Canadian side and did not hit. She landed passengers at Navy Island, reached Schlosser about three in the afternoon, made two further trips to the island, and was back at the landing about six. In the evening about twenty-three people, the master said all of them American citizens, asked to stay aboard. He put the company, passengers and crew, at thirty-three.",
        "Schlosser is easy to promote into a fort. Miller’s geographical note, drawn from the congressional documents, keeps it smaller: a landing, a storehouse, a tavern, on the American shore a short way above the falls. The old Fort Schlosser stood lower down and was already abandoned. The night’s argument was about a mooring, not a rampart.",
      ],
    },
    {
      heading: "Midnight, and the count that shrank",
      paragraphs: [
        "The British explanation, given later by Lord Ashburton and attributed by him to the officer who led the boats, is that the expedition was sent to take the Caroline where she was expected to be, on Navy Island, which was British ground. She was not there. Ashburton says the rebel leader’s orders had been disobeyed, and that the officer discovered only as he came round the island that the steamer was moored to the other shore. He took her anyway. His government approved. The American complaint does not depend on calling that story false. It depends on the shore. Whatever the party had expected, the seizure happened in New York.",
        "Who led it is stable in the compilation. Commander Andrew Drew of the Royal Navy had the boats. He acted under Colonel Allan Napier MacNab, at Chippewa, and MacNab was acting under the orders of his superior. How many men came with Drew is not stable. The master’s deposition says about seventy or eighty armed men boarded at midnight, with muskets, swords, and cutlasses, against a company that tried to escape. Miller, citing the House document, puts Drew’s force at forty-five men in five boats. Almost Lore will not average seventy and forty-five into a phantom company. The attackers were a British force from Chippewa. The integer is a disagreement in the file.",
        "What they did to the boat is the part both sides describe in the same verbs. They set her on fire, cut her loose, and sent her into the current. They could not, on the British telling, tow her off against the stream, and burning her in the stream was explained as a way to keep the fire off the landing. Beacon lights and cheering were seen and heard afterward on the Canadian side. The early American account, the one the master gave and the towns repeated, then added a horror the investigation did not keep: of thirty-three people on board, twenty-one had been found, Durfee was dead on the dock from a musket ball, several were wounded, and twelve were missing. It was generally believed, Moore writes, that the missing lay wounded in the steamer and went with her over the falls.",
        "The later investigation, as the same digest records it, retired the twelve. The only persons from the boat who remained missing, in that second pass, were Durfee and the cabin boy, Johnson, known as Little Billy, and the investigation’s conclusion was that both had been shot leaving the steamer. Durfee’s body was the one already on the dock, so “missing” is an awkward word for him; what the digest is clear about is the rumor. Two others had been carried into Canada and were then released. The twelve men in the burning hull do not survive that correction. Durfee on the dock is the death the file still names. Drew, publishing his own narrative in 1864, titled it as a descent over the falls, and Ashburton’s note speaks of the vessel floated down the falls. Contemporary prints did the rest. A picture is not a measurement of where a hull breaks up in that current. This essay will say what the orders achieved — a steamer fired and cast off above the cataract — and will not certify the souvenir.",
      ],
    },
    {
      heading: "The boast and the court that would not yield",
      paragraphs: [
        "Washington did not treat the night as a private brawl. John Forsyth, Secretary of State, wrote to Henry Fox, the British minister, that the destruction of property and the killing of citizens on the soil of New York, while the President was trying to quiet the frontier, would be the subject of a demand for redress. General Winfield Scott was sent up with letters asking the governors of New York and Vermont for militia. On 6 February 1838 Fox answered. He enclosed the account from Sir Francis Bond Head, lieutenant governor of Upper Canada, avowed that the force was MacNab’s, and called the destruction necessary self-defense against what he termed a pirate steamer, at a moment when, he said, American law was not actually in force on that border. On 22 May the American minister in London, Andrew Stevenson, demanded reparation. Palmerston acknowledged it on 6 June and promised to consider it. The consideration lasted years.",
        "The case came back as a man. Alexander McLeod, a Canadian, was arrested in New York and charged with murder and arson for Durfee’s death. The Historical Society of the New York Courts places that arrest in November 1840, in Lewiston, and says he had boasted of taking part in the raid and of killing an American. Moore’s digest, written as diplomatic history, places the turn in the correspondence in March 1841 and describes the boast more narrowly: while drunk, McLeod claimed an effective part in the destruction of the Caroline. The two sentences are not the same boast. One of them includes a personal claim to the shot. This essay will not decide, from a tavern story, which words he used. It will not pretend the digest and the court history share one calendar day for the arrest.",
        "Palmerston then did what he had not done in a hurry in 1838. He avowed the destruction as a public act of force, done in self-defense by people in the Queen’s service, and demanded that McLeod be released. Because the prisoner was held under the law of New York, the federal government could not hand him over. Governor William H. Seward’s state was not going to treat a homicide charge as a note from the State Department. In July 1841 McLeod’s lawyers sought a writ before judges of the New York Supreme Court of Judicature. Justice Esek Cowen’s opinion drew the line the court was willing to draw: immunity for a public act of force belonged to a state of war, and Britain and the United States were not at war. The court remanded him for trial and moved the venue from Niagara County to Oneida County.",
        "The trial opened on 4 October 1841 in the circuit court at Utica, Judge Philo Gridley presiding. The New York attorney general, Willis Hall, prosecuted. Joshua A. Spencer defended. The defense the jury accepted was not Webster’s doctrine and not Palmerston’s avowal. Witnesses placed McLeod at Chippewa, not in the boats. The published account of the trial puts the deliberation at about twenty minutes. The verdict was not guilty. An alibi ends a murder case. It does not decide whether the raid was a legal act of the Crown. Britain had demanded a release and treated the prosecution as a matter that touched the peace; Ashburton, looking back in 1842, wrote that the business had more than once endangered it. The rope was not used. The argument about the night at Schlosser was still open, because the man in the dock had been cleared by being somewhere else.",
      ],
    },
    {
      heading: "A rule both sides recited",
      paragraphs: [
        "Daniel Webster, Secretary of State under Tyler, had already put the American test on paper while McLeod was still in the courts. On 24 April 1841 he wrote to Fox that a nation has a right of self-defense, and that the right is not a license. Where the alleged defense consists of hostile acts inside the territory of a power at peace, nothing less than a clear and absolute necessity will justify them. The sentence that left the dispatch and entered every later argument is his burden of proof, shifted onto London: it would be for the British government to show “a necessity of self-defence, instant, overwhelming, leaving no choice of means, and no moment for deliberation.” It would also have to show that the Canadian authorities, even if that necessity let them cross the line at all, did nothing unreasonable or excessive — that the act stayed inside the necessity that was supposed to excuse it. Webster then stacked the facts as the United States understood them: a vessel moored to the shore, unarmed men asleep, a night attack, a fire, a current above the cataract. He did not believe a necessity for all of that had existed. He also refused the British word “pirates” for Americans who had gone to a rebellion. They might be criminals under the neutrality laws. They were not, in his usage, pirates.",
        "The notes that closed the quarrel were exchanged in Washington in the summer of 1842, between Webster and Lord Ashburton, alongside the talks that produced the Treaty of Washington. The Caroline is not an article of that treaty. Miller says so plainly. It was settled, if settled is the word, in three letters: Webster on 27 July, Ashburton on 28 July, Webster on 6 August.",
        "Ashburton accepted the principle and spent the letter on the facts. He dated the occupation of Navy Island to 16 December. He said the force there had grown in the open, that remonstrance had failed, and that guns on the island — he says twelve pieces — were firing on the Canadian shore. Those are his numbers, offered as justification, and the American replies in this correspondence do not pause to audit them one by one. He asked how long a government was obliged to wait for the neighbor’s authorities. He argued that Drew’s discovery, in the dark, that the steamer lay against the American bank was itself “no moment left for deliberation.” And he gave the sentence London had withheld in 1838. Looking back, what was most to be regretted was that “some explanation and apology for this occurrence was not immediately made.” He was instructed to say that a violation of territory had occurred, that his government took it as serious, and that it would deprecate a repetition. He did not offer that as a confession that the necessity had been missing. He offered it as regret that the explanation had been late, wrapped around a justification he still believed.",
        "Webster’s reply of 6 August took the regret and left the justification where it was. The President was glad the two governments described the exception in the same words: necessity of self-defense, instant, overwhelming, leaving no choice of means and no moment for deliberation. The remaining difference was whether the Caroline was such a case. Given the time that had passed, given Ashburton’s assurance that no slight to American sovereignty had been intended, given the acknowledgment that territory had been violated and that an explanation and apology had been due at the time, the President would receive those assurances “and will make this subject, as a complaint of violation of territory, the topic of no further discussion between the two Governments.” That is a closing, not a verdict. Nobody in these notes found, as a joint fact, that the midnight burning had met the test. They agreed on the test, recorded that an apology for the crossing had been due, and agreed to stop litigating the crossing.",
        "The same letters covered McLeod, after the jury had already freed him. Webster repeated that a person who acts by the command of his sovereign is not, for that public act, answerable in the ordinary courts of another state. He also repeated the American constraint: in a constitutional government a prisoner charged with a grave crime is discharged by a court, not by a minister’s letter. The delay had been regretted. The acquittal had made a further appeal unnecessary. Congress, Webster said, could decide what procedure should exist the next time. On 29 August 1842 it enacted a statute aimed at cases of McLeod’s kind, so the question would have a federal door. The Caroline doctrine, as later writers named Webster’s sentence, is that procedural afterlife as much as it is a theory of war. It is a standard recited in 1842 by both foreign offices, attached to a raid neither of them was willing to reopen, and left stricter on the page than the night had been on the river.",
      ],
    },
    {
      heading: "Why the hook is not the essay",
      paragraphs: [
        "A compressed line needs the falls. The falls are a machine for awe, and awe does not ask whether twelve men were in the hull or whether the later investigation had already reduced the missing to a dead man on the dock and a cabin boy. The line also needs a war that almost was, preferably with a match already lit. The match in this file is real and duller. A rebellion occupied an island the boundary assigned to Britain. A steamer supplied it from New York. A cutting-out party followed the steamer to the wrong shore, or to the shore the night had made the only shore, and burned it. One killing is firm. The rest of the body count is a rumor the digest itself retired.",
        "The near-miss that can survive the note is the one after the fire was out. A Canadian boasted, and New York charged him. Britain called the raid a public act and demanded a release the federal government could not order and a state court would not grant on a writ. A jury acquitted him for being at Chippewa. Two years of that, Ashburton wrote, had more than once endangered the peace. The peace was kept by an apology for the violation and a shared sentence about necessity — and by leaving unsettled the only question the sentence was written to decide.",
      ],
    },
  ],
};
